export interface VehicleFuelProfile {
  id: string
  name: string
  make: string
  category: 'superbike' | 'motorcycle' | 'turbo-car' | 'luxury-car' | 'classic'
  engine: string
  compressionRatio: string
  recommendedOctane: number
  e20Compatible: boolean
  riskLevel: 'critical' | 'high' | 'moderate' | 'safe'
  summary: string
  fuelGuidance: string
  vulnerabilities: string[]
  recommendedFuels: string[]
}

export const VEHICLES_DATA: VehicleFuelProfile[] = [
  {
    id: 'ktm-duke-390',
    name: 'KTM 390 Duke / RC 390 / Adventure',
    make: 'KTM',
    category: 'motorcycle',
    engine: '398.7cc Single-cylinder DOHC (Gen 3) / 373.2cc (Gen 2)',
    compressionRatio: '12.8:1',
    recommendedOctane: 95,
    e20Compatible: false,
    riskLevel: 'high',
    summary: 'High-compression single running at high thermal stress. E20 leads to significant knocking, higher operating temperatures, and fuel pump filter clogging.',
    fuelGuidance: 'Fill XP100 or poWer100 (E0) whenever available. If unavailable, use XP95 with an ethanol fuel stabilizer. Never leave E20 sitting in the tank for more than 2 weeks.',
    vulnerabilities: [
      'High engine knocking and pre-ignition on standard 91 RON E20',
      'In-tank fuel pump strainer gumming from degraded ethanol blends',
      'Higher radiator fan run-times due to increased combustion temperatures',
      'Injector fouling leading to jerky low-RPM throttle transitions',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'BPCL Speed 97 (Minimum)'],
  },
  {
    id: 'royal-enfield-classic-350',
    name: 'Royal Enfield Classic 350 / Bullet / Meteor (J-Series)',
    make: 'Royal Enfield',
    category: 'motorcycle',
    engine: '349cc Air-Oil Cooled SOHC J-Series',
    compressionRatio: '9.5:1',
    recommendedOctane: 91,
    e20Compatible: true,
    riskLevel: 'moderate',
    summary: 'While J-series engine metallurgy supports E20, long-term tank condensation and phase separation cause sluggish acceleration, rough idle, and tank bottom rust.',
    fuelGuidance: 'Compatible with standard fuel, but E0 petrol produces smoother idle, noticeable throttle response improvements, and eliminates water accumulation during monsoon parking.',
    vulnerabilities: [
      'Moisture absorption causing water pooling at tank base during rainy months',
      'Rough cold starts after bike is parked for more than 7 days',
      'Loss of 6-8% fuel economy on E20 compared to pure E0 petrol',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'Standard 91 RON (fresh only)'],
  },
  {
    id: 're-himalayan-450',
    name: 'Royal Enfield Himalayan 450 / Guerrilla 450',
    make: 'Royal Enfield',
    category: 'motorcycle',
    engine: '452cc Liquid-Cooled DOHC Sherpa Engine',
    compressionRatio: '11.5:1',
    recommendedOctane: 95,
    e20Compatible: true,
    riskLevel: 'moderate',
    summary: 'Royal Enfield\'s first high-revving liquid-cooled motor requires high-octane fuel to prevent mid-range knock on mountain climbs at high altitudes.',
    fuelGuidance: 'For touring Ladakh, Spiti, and high-altitude mountain passes, fill E0 (XP100/poWer100) before entering remote zones to prevent cold stalling and vapor lock.',
    vulnerabilities: [
      'Cold-temperature hard starts above 10,000 ft with blended ethanol',
      'Engine knock under high luggage payload and steep uphill loads on 91 RON',
      'Phase separation in extreme cold sub-zero Himalayan night stops',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'IOCL XP95'],
  },
  {
    id: 'yamaha-r15-mt15',
    name: 'Yamaha YZF-R15 V4 / MT-15 V2',
    make: 'Yamaha',
    category: 'motorcycle',
    engine: '155cc Liquid-cooled SOHC 4-valve with VVA',
    compressionRatio: '11.6:1',
    recommendedOctane: 91,
    e20Compatible: true,
    riskLevel: 'moderate',
    summary: 'High-revving VVA motor revs up to 10,500 RPM. Ethanol blending degrades throttle crispness at high RPM and leaves deposits on injector nozzles.',
    fuelGuidance: 'Runs reliably on standard petrol, but filling E0 petrol every 2-3 tanks cleans injectors naturally and restores top-end power delivery.',
    vulnerabilities: [
      'Loss of peak top-end surge above 7,400 RPM when VVA engages',
      'Corrosive build-up on fine injector micro-orifices',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'IOCL XP95'],
  },
  {
    id: 'kawasaki-ninja-zx10r-z900',
    name: 'Kawasaki Ninja ZX-10R / Z900 / Ninja 650',
    make: 'Kawasaki',
    category: 'superbike',
    engine: '998cc Inline-4 (ZX-10R) / 948cc Inline-4 (Z900)',
    compressionRatio: '13.0:1 (ZX-10R) / 11.8:1 (Z900)',
    recommendedOctane: 95,
    e20Compatible: false,
    riskLevel: 'critical',
    summary: 'Japanese superbikes are strictly engineered for high-octane pure fuel. Ethanol corrodes specialized high-pressure fuel lines and induces dangerous high-RPM detonation.',
    fuelGuidance: 'STRICT REQUIREMENT: Use ONLY 0% ethanol XP100 or poWer100. Never run standard E20. If emergency fuel is needed, keep revs below 4,000 RPM and drain tank immediately.',
    vulnerabilities: [
      'Catastrophic piston crown detonation at 10,000+ RPM on 91 RON E20',
      'Fuel rail rubber seal degradation and fuel leak hazards',
      'Oxygen sensor and catalytic converter fouling from unburned ethanol radicals',
      'Voided factory engine warranty if ethanol damage is diagnosed',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'BPCL Speed 100 (E0)'],
  },
  {
    id: 'bmw-s1000rr-g310r',
    name: 'BMW Motorrad S1000RR / M1000R / G310R',
    make: 'BMW Motorrad',
    category: 'superbike',
    engine: '999cc ShiftCam Inline-4 (S1000RR) / 313cc Single (G310R)',
    compressionRatio: '13.3:1 (S1000RR) / 10.9:1 (G310R)',
    recommendedOctane: 98,
    e20Compatible: false,
    riskLevel: 'critical',
    summary: 'BMW ShiftCam engines require minimum 98 RON fuel. E20 petrol causes instant knock sensor retard, dropping engine output by up to 25 BHP.',
    fuelGuidance: 'Always fuel with XP100 (100 Octane E0) or poWer100. Never use standard pumps. Check E0 Finder map before inter-city Sunday morning rides.',
    vulnerabilities: [
      'ShiftCam timing gear retard from persistent knock detection',
      'Premature failure of piezoelectric injectors',
      'High-pressure fuel pump (HPFP) cavitation',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)'],
  },
  {
    id: 'triumph-speed-400',
    name: 'Triumph Speed 400 / Scrambler 400 X',
    make: 'Triumph',
    category: 'motorcycle',
    engine: '398cc Liquid-cooled 4-valve DOHC TR-Series',
    compressionRatio: '12.0:1',
    recommendedOctane: 95,
    e20Compatible: true,
    riskLevel: 'moderate',
    summary: 'High 12.0:1 compression ratio benefits substantially from 95+ octane. While E20 compliant, ethanol degrades low-end torque delivery and fuel efficiency.',
    fuelGuidance: 'XP95 is acceptable for daily commutes. For spirited weekend rides or highway touring, XP100 E0 gives crisper throttle and eliminates low-end hesitation.',
    vulnerabilities: [
      'Low-speed stall propensity with low-octane blended fuel',
      'Fuel tank inner coating deterioration during long stationary periods',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'IOCL XP95'],
  },
  {
    id: 'skoda-vw-tsi',
    name: 'Skoda Kushaq / Slavia & VW Taigun / Virtus (1.0 & 1.5 TSI)',
    make: 'Skoda / Volkswagen',
    category: 'turbo-car',
    engine: '1.0L TSI 3-cylinder (115 PS) / 1.5L TSI EVO 4-cylinder (150 PS) with ACT',
    compressionRatio: '10.5:1 (1.0 TSI) / 12.5:1 (1.5 TSI)',
    recommendedOctane: 95,
    e20Compatible: true,
    riskLevel: 'high',
    summary: 'Direct injection (TSI) engines are highly susceptible to intake valve carbon deposits and high-pressure fuel pump (HPFP) wear from hydroscopic ethanol blends.',
    fuelGuidance: 'Volkswagen Group recommends minimum 95 RON fuel. E0 petrol (XP100/poWer100) or high-grade XP95 ensures smooth cylinder deactivation (ACT) and protects delicate direct injectors.',
    vulnerabilities: [
      'Severe direct injector tip carbon fouling requiring chemical decarb',
      'High Pressure Fuel Pump (HPFP) seal wear from ethanol lubricity loss',
      'Jerky DSG/manual low-speed creep in stop-and-go traffic',
      'Misfire codes (P0300) when fuel experiences phase separation in tank',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'IOCL XP95'],
  },
  {
    id: 'mahindra-thar-scorpio-mstallion',
    name: 'Mahindra Thar / Scorpio-N / XUV700 (2.0L mStallion Turbo Petrol)',
    make: 'Mahindra',
    category: 'turbo-car',
    engine: '2.0L TGDi 4-cylinder mStallion (150 - 200 PS)',
    compressionRatio: '9.6:1',
    recommendedOctane: 91,
    e20Compatible: true,
    riskLevel: 'moderate',
    summary: 'High-output turbocharged petrol engine producing up to 380 Nm. Highly thirsty on E20; ethanol blend causes an 8-12% drop in highway fuel mileage.',
    fuelGuidance: 'Using E0 petrol provides noticeable gains in fuel range per tank — critical for long Thar road trips in remote terrain where pumps are 150 km apart.',
    vulnerabilities: [
      'Substantial mileage drop (often falling to 6-8 km/l in city traffic on E20)',
      'Turbo lag accentuated by lower energy density of ethanol',
      'Condensation inside large 57L-60L fuel tanks during seasonal temperature swings',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'IOCL XP95'],
  },
  {
    id: 'hyundai-kia-turbo-gdi',
    name: 'Hyundai Creta / Verna & Kia Seltos (1.5L Turbo GDi)',
    make: 'Hyundai / Kia',
    category: 'turbo-car',
    engine: '1.5L Smartstream T-GDi (160 PS / 253 Nm)',
    compressionRatio: '10.5:1',
    recommendedOctane: 95,
    e20Compatible: true,
    riskLevel: 'moderate',
    summary: 'Direct-injected turbo producing class-leading power. Benefits from higher octane and ethanol-free fuel to prevent carbon build-up on back of intake valves.',
    fuelGuidance: 'Fill E0 or 95+ octane whenever planning highway sprints to ensure instant boost response and cooler combustion chamber temperatures.',
    vulnerabilities: [
      'Direct-injection valve deposit accumulation (no port wash)',
      'Spark retard under sudden kick-down acceleration on standard 91 RON E20',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'IOCL XP95'],
  },
  {
    id: 'german-luxury-bmw-merc-audi',
    name: 'Mercedes-Benz C/E/GLC & BMW 3/5/X3 & Audi A4/A6/Q5',
    make: 'Mercedes / BMW / Audi',
    category: 'luxury-car',
    engine: '2.0L Turbo 4-cyl / 3.0L Turbo Inline-6 / V6',
    compressionRatio: '10.5:1 - 11.5:1',
    recommendedOctane: 98,
    e20Compatible: false,
    riskLevel: 'critical',
    summary: 'European luxury cars are calibrated for European EN 228 premium fuels. Standard Indian E20 triggers check engine lights (CEL) and degrades synthetic fuel lines.',
    fuelGuidance: 'Fill XP100 or poWer100 as the primary fuel. Standard E20 should only be used in emergency situations and never under aggressive driving.',
    vulnerabilities: [
      'Frequent Check Engine Lights (P0171 / P0174 System Too Lean from ethanol oxygenation)',
      'Premature catalytic converter failure ($2,000+ repair cost)',
      'Rough idle and cold start stumble',
      'Potential rejection of warranty claims for fuel system components',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'BPCL Speed 100 (E0)'],
  },
  {
    id: 'vintage-carbureted-classics',
    name: 'Vintage & Carbureted Cars & Motorcycles (Pre-2010 Models)',
    make: 'All Classic Makes (Maruti 800, Zen, RD350, RX100, Ambassador, Contessa)',
    category: 'classic',
    engine: 'Naturally aspirated carbureted engines',
    compressionRatio: '8.0:1 - 9.5:1',
    recommendedOctane: 87,
    e20Compatible: false,
    riskLevel: 'critical',
    summary: 'PRE-2010 CARBURETED ENGINES HAVE ZERO ETHANOL RESISTANCE. Ethanol dissolves natural rubber floats, degrades brass jets, and rots cork gaskets within weeks.',
    fuelGuidance: 'MUST USE 0% ETHANOL (E0) FUEL EXCLUSIVELY. If E0 is unreachable, use specialized marine-grade ethanol stabilizer and replace all rubber fuel hoses with fluoroelastomer (Viton).',
    vulnerabilities: [
      'Carburetor float pin sticking and fuel overflow hazards',
      'Corrosion of die-cast zinc/aluminum carburetor bodies (white powdery galvanic corrosion)',
      'Fuel line cracking, swelling, and engine bay fire hazard',
      'Total engine seizure from water-ethanol phase separation in fuel tank',
    ],
    recommendedFuels: ['IOCL XP100 (E0)', 'HPCL poWer100 (E0)', 'Pure unblended petrol with fuel stabilizer'],
  },
]
